on:
  release:
    types: [created]

jobs:
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Currently "Windows on arm64" is experimental, only supporting windows/amd64 for now
        goos: [ windows ]
        goarch: [ amd64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./src/cmd/qb-list"
          extra_files: LICENSE README.md